greeting:
  message: "hello"

"%test":
  quarkus:
    oidc:
      enabled: false

quarkus:
  application:
    name: ${APPLICATION_NAME:lucky-parking}
  oidc:
    auth-server-url: ${IDENTITY_PROVIDER_URL:http://keycloak.kubernetes.docker.internal/auth/realms/${APPLICATION_NAME:lucky-parking}}
#    client-id: mobile-app
#    application-type: service
#
#resteasy:
#  role:
#    based:
#      security: true
