domain: docker.internal
subdomain: kubernetes

ingress:
  tls:
    secretName: #no value turn off TLS
    certificate: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----

backend:
  image:
    name: backend:latest
    pullPolicy: Never
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"