domain: docker.internal
subdomain: kubernetes

owner:
  email:

ingress:
  tls:
    enabled: false

backend:
  image:
    name: backend:latest
    pullPolicy: Never
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

keycloak:
  realm: |-
    {
      "id": "lucky-parking",
      "realm": "lucky-parking"
    }