domain: docker.internal
subdomain: kubernetes

ingress:
  tls:
    enabled: false
    acme:
      email: my@mail.com
      sever: https://acme-staging-v02.api.letsencrypt.org/directory

backend:
  image:
    name: backend:latest
    pullPolicy: Never
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

keycloak:
  realm: |-
    {
      "id": "lucky-parking",
      "realm": "lucky-parking"
    }