apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    {{- include "application.labels" . | nindent 4 }}
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "backend.container.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "application.labels" . | nindent 8 }}
    {{- include "backend.container.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.backend.image.name }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            requests:
              cpu: {{.Values.backend.resources.requests.cpu}}
              memory: {{.Values.backend.resources.requests.memory}}
            limits:
              cpu: {{.Values.backend.resources.limits.cpu}}
              memory: {{.Values.backend.resources.limits.memory}}