apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    {{- include "application.labels" . | nindent 4 }}
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "container.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "application.labels" . | nindent 8 }}
    {{- include "container.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend-container
          image: lucky-parking:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3