apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proxy
  labels:
    {{- include "application.labels" . | nindent 4 }}
    app.kubernetes.io/name: proxy
    app.kubernetes.io/component: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if (.Values.ingress.tls.secretName)}}
    kubernetes.io/ingress.allow-http: "false"
    {{- end }}
spec:
  {{- if (.Values.ingress.tls.secretName)}}
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "backend.service.name" . }}
                port:
                  name: {{ include "backend.service.port" . }}
            path: /
            pathType: Prefix