{{ if (.Values.ingress.tls.enabled)}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Values.subdomain }}
spec:
  acme:
    email: {{ .Values.ingress.tls.acme.email }}
    server: {{ .Values.ingress.tls.acme.sever }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
  {{ end }}