apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.service.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
  {{- include "keycloak.container.labels" . | nindent 4 }}
  ports:
    - name: {{ include "keycloak.service.port" . }}
      protocol: TCP
      port: 8080
      targetPort: 8080
