apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    {{- include "application.labels" . | nindent 4 }}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "keycloak.container.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "application.labels" . | nindent 8 }}
    {{- include "keycloak.container.labels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak-container
          image: quay.io/keycloak/keycloak:15.0.2
          env:
            - name: KEYCLOAK_USER
              value: {{ .Values.keycloak.admin.name}}
            - name: KEYCLOAK_PASSWORD
              value: {{ .Values.keycloak.admin.password}}
            - name: KEYCLOAK_IMPORT
              value: "/tmp/realm.json"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
          volumeMounts:
            - mountPath: "/tmp"
              name: realm
              readOnly: true
      volumes:
        - name: realm
          configMap:
            name: application-config
            items:
              - key: "realm-configuration"
                path: "realm.json"